### ISSUE TITLE
RTX 3090 but Out of Memory

### ISSUE THREAD

**Issue by gyjung0212** [River-Zhang/ICEdit#25]
```Traceback (most recent call last):
  File "/home/test/work/text_guided_image_editing/ICEdit/scripts/inference.py", line 66, in <module>
    result_image = pipe(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/flux/pipeline_flux_fill.py", line 916, in __call__
    noise_pred = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 161, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 691, in pre_forward
    module.to(self.execution_device)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 1077, in to
    return super().to(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1340, in to
    return self._apply(convert)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1326, in convert
    return t.to(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.00 MiB. GPU 0 has a total capacity of 23.69 GiB of which 15.69 MiB is free. Process 293358 has 23.67 GiB memory in use. Of the allocated memory 21.41 GiB is allocated by PyTorch, and 1.95 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

<img width="712" alt="Image" src="https://github.com/user-attachments/assets/7ce504a3-b725-475e-8aaa-92ee89c16e5c" />

I have RTX 3090 *4 .
And set pipe.enable_model_cpu_offload() .
but I got torch.OutOfMemoryError.

**Comment by HorizonWind2004** [comment]
You can see this [issue](https://github.com/River-Zhang/ICEdit/issues/16).

**Comment by gyjung0212** [comment]
> You can see this [issue](https://github.com/River-Zhang/ICEdit/issues/16).

Is there any other way without using comfyui?

**Comment by HorizonWind2004** [comment]
My version is:
NVIDIA-SMI 555.42.02              Driver Version: 555.42.02      CUDA Version: 12.5

If it still cannot work, you can try our ComfyUI demo, which needs only 14GB.

**Comment by gyjung0212** [comment]
> My version is: NVIDIA-SMI 555.42.02 Driver Version: 555.42.02 CUDA Version: 12.5
> 
> If it still cannot work, you can try our ComfyUI demo, which needs only 14GB.

My linux server can't use GUI. So I cannot use ComfyUI.
Does cuda version affect memory usage?

**Comment by HorizonWind2004** [comment]
> > You can see this [issue](https://github.com/River-Zhang/ICEdit/issues/16).
> 
> Is there any other way without using comfyui?

I don't know why you meet OOM :( . If it still cannot work, you may try fp8 version :(

https://huggingface.co/jackzheng/flux-fill-FP8

**Comment by gyjung0212** [comment]
> > > You can see this [issue](https://github.com/River-Zhang/ICEdit/issues/16).
> > 
> > 
> > Is there any other way without using comfyui?
> 
> I don't know why you meet OOM :( . If it still cannot work, you may try fp8 version :(
> 
> https://huggingface.co/jackzheng/flux-fill-FP8

I'll try it...
Thank you :)

**Comment by River-Zhang** [comment]
We're also utilizing a Linux server, and we've successfully run ComfyUI on it. Notably, the official ComfyUI demo consumes approximately 14GB of VRAM.

**Comment by gyjung0212** [comment]
> We're also utilizing a Linux server, and we've successfully run ComfyUI on it. Notably, the official ComfyUI demo consumes approximately 14GB of VRAM.
> 
> Ports can be forwarded using VSCode and this way you can use ComfyUI I guess.


Thank you for your kind reply :)

**Comment by ali0une** [comment]
Hi there.

You need to pass the --enable-model-cpu-offload True argument to the scripts/demo_gradio.py or scripts/inference.py

```bash
(venv) user@whatever:~/whatever/Icedit$ python scripts/gradio_demo.py --port 7860 --enable-model-cpu-offload True
```

**Comment by gyjung0212** [comment]
@ali0une @HorizonWind2004 @River-Zhang @hayd-zju 

I solved it using CUDA 11.8. !!
